// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "behaviac/behaviac.h"

#include "behaviac_generated_behaviors.h"

namespace behaviac
{
	class CppGenerationManager : GenerationManager
	{
	public:
		CppGenerationManager()
		{
			SetInstance(this);
		}

		virtual void RegisterBehaviorsImplement()
		{
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("FirstBT", bt_FirstBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("main", bt_main::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("ParentBT", bt_ParentBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("SecondBT", bt_SecondBT::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("Struct", bt_Struct::Create);
			Workspace::GetInstance()->RegisterBehaviorTreeCreator("sub", bt_sub::Create);
		}
	};

	CppGenerationManager _cppGenerationManager_;
}
