// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_FirstEnum : ICompareValue<FirstEnum>
	{
		public override bool Equal(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_FirstStruct : ICompareValue<FirstStruct>
	{
		public override bool Equal(FirstStruct lhs, FirstStruct rhs)
		{
			return (lhs.s1 == rhs.s1) && (lhs.s2 == rhs.s2);
		}
		public override bool NotEqual(FirstStruct lhs, FirstStruct rhs)
		{
			return !Equal(lhs, rhs);
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		class CInstanceConst_FirstStruct : CInstanceConst<FirstStruct>
		{
			IInstanceMember _s1;
			IInstanceMember _s2;

			public CInstanceConst_FirstStruct(string typeName, string valueStr) : base(typeName, valueStr)
			{
				List<string> paramStrs = behaviac.StringUtils.SplitTokensForStruct(valueStr);
				Debug.Check(paramStrs != null && paramStrs.Count == 2);

				_s1 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[0]);
				_s2 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_s1 != null);
				Debug.Check(_s2 != null);

				_value.s1 = ((CInstanceMember<int>)_s1).GetValue(self);
				_value.s2 = ((CInstanceMember<int>)_s2).GetValue(self);
			}
		};

		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_FisrtAgent_m1 : CAgentMethodVoidBase
		{
			CInstanceMember<string> _value;

			public CMethod_FisrtAgent_m1()
			{
			}

			public CMethod_FisrtAgent_m1(CMethod_FisrtAgent_m1 rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_FisrtAgent_m1(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_value = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_value != null);

				string value = ((CInstanceMember<string>)_value).GetValue(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				((FisrtAgent)agent).m1(ref value);
				_value.SetValue(self, value);
			}
		}

		private class CMethod_FisrtAgent_SayHello : CAgentMethodVoidBase
		{
			CInstanceMember<string> _value;

			public CMethod_FisrtAgent_SayHello()
			{
			}

			public CMethod_FisrtAgent_SayHello(CMethod_FisrtAgent_SayHello rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_FisrtAgent_SayHello(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_value = (CInstanceMember<string>)AgentMeta.ParseProperty<string>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_value != null);

				string value = ((CInstanceMember<string>)_value).GetValue(self);
				Agent agent = Utils.GetParentAgent(self, _instance);

				object[] paramArray = new object[] { value };
				AgentMetaVisitor.ExecuteMethod(((FisrtAgent)agent), "SayHello", paramArray);
				_value.SetValue(self, (string)paramArray[0]);
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 1414843750;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// FisrtAgent
			meta = new AgentMeta(558188002);
			AgentMeta._AgentMetas_[2989156771] = meta;
			meta.RegisterMemberProperty(1870413056, new CMemberProperty<int>("P2", delegate(Agent self, int value) { ((FisrtAgent)self).P2 = value; }, delegate(Agent self) { return ((FisrtAgent)self).P2; }));
			meta.RegisterMemberProperty(1144200279, new CMemberProperty<SecondAgent>("pInstance", delegate(Agent self, SecondAgent value) { ((FisrtAgent)self)._set_pInstance(value); }, delegate(Agent self) { return ((FisrtAgent)self)._get_pInstance(); }));
			meta.RegisterMemberProperty(2350374053, new CMemberProperty<FirstStruct>("pp3", delegate(Agent self, FirstStruct value) { ((FisrtAgent)self)._set_pp3(value); }, delegate(Agent self) { return ((FisrtAgent)self)._get_pp3(); }));
			meta.RegisterMemberProperty(1756271184, new CMemberProperty<FirstEnum>("type", delegate(Agent self, FirstEnum value) { ((FisrtAgent)self)._set_type(value); }, delegate(Agent self) { return ((FisrtAgent)self)._get_type(); }));
			meta.RegisterMethod(3345343196, new CAgentMethodVoid<int>(delegate(Agent self, int valur) { }) /* event_task */);
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { FisrtAgent.LogMessage(param0); }));
			meta.RegisterMethod(1759647744, new CMethod_FisrtAgent_m1());
			meta.RegisterMethod(4211940295, new CAgentMethod<int, int>(delegate(Agent self, int s) { return ((FisrtAgent)self).PRe(s); }));
			meta.RegisterMethod(1505908390, new CMethod_FisrtAgent_SayHello());
			meta.RegisterMethod(2065006847, new CAgentMethodVoid<int>(delegate(Agent self, int value) { }) /* t1 */);
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// SecondAgent
			meta = new AgentMeta(3206454578);
			AgentMeta._AgentMetas_[2432194202] = meta;
			meta.RegisterMemberProperty(1311394465, new CMemberProperty<int>("p3", delegate(Agent self, int value) { ((SecondAgent)self)._set_p3(value); }, delegate(Agent self) { return ((SecondAgent)self)._get_p3(); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { SecondAgent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<FisrtAgent>("FisrtAgent");
			AgentMeta.Register<SecondAgent>("SecondAgent");
			AgentMeta.Register<FirstEnum>("FirstEnum");
			ComparerRegister.RegisterType<FirstEnum, CompareValue_FirstEnum>();
			AgentMeta.Register<FirstStruct>("FirstStruct");
			ComparerRegister.RegisterType<FirstStruct, CompareValue_FirstStruct>();

			Agent.RegisterInstanceName<SecondAgent>("SecondAgentInstance");
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<FisrtAgent>("FisrtAgent");
			AgentMeta.UnRegister<SecondAgent>("SecondAgent");
			AgentMeta.UnRegister<FirstEnum>("FirstEnum");
			AgentMeta.UnRegister<FirstStruct>("FirstStruct");

			Agent.UnRegisterInstanceName<SecondAgent>("SecondAgentInstance");
			return true;
		}
	}
}
