// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class FisrtAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE FisrtAgent
///<<< END WRITING YOUR CODE
{
	public int P2 = 0;

	private SecondAgent pInstance = null;
	public void _set_pInstance(SecondAgent value)
	{
		pInstance = value;
	}
	public SecondAgent _get_pInstance()
	{
		return pInstance;
	}

	private FirstStruct pp3 = new FirstStruct();
	public void _set_pp3(FirstStruct value)
	{
		pp3 = value;
	}
	public FirstStruct _get_pp3()
	{
		return pp3;
	}

	private FirstEnum type = FirstEnum.e1;
	public void _set_type(FirstEnum value)
	{
		type = value;
	}
	public FirstEnum _get_type()
	{
		return type;
	}

	public void m1(ref string value)
	{
///<<< BEGIN WRITING YOUR CODE m1
        behaviac.Debug.LogWarning("ceshi ");
///<<< END WRITING YOUR CODE
	}

	public int PRe(int s)
	{
///<<< BEGIN WRITING YOUR CODE PRe
        s++;
        behaviac.Debug.LogWarning("ceshi "+ s);
        return s;
///<<< END WRITING YOUR CODE
	}

	private void SayHello(ref string value)
	{
///<<< BEGIN WRITING YOUR CODE SayHello
        ///
        behaviac.Debug.LogWarning("Hello Behaviac!"+value);

        ///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART
    private void InitPlayer()
    {
        behaviac.Debug.LogWarning("InitPlayer");

        bool bRet = this.btload("FirstBT");
        if (bRet)
        {
            this.btsetcurrent("FirstBT");
        }
        bool bSecond = this.btload("SecondBT");
        if (bSecond)
        {
            this.btsetcurrent("SecondBT");
        }
        behaviac.Agent.BindInstance(_get_pInstance(), "SecondAgentInstance");

        bool bParent = this.btload("ParentBT");
        if (bParent)
        {
            this.btsetcurrent("ParentBT");
        }
        bool main = this.btload("main");
        if (main)
        {
            this.btsetcurrent("main");
        }
        bool sub = this.btload("sub");
        if (sub)
        {
            this.btsetcurrent("sub");
        }
        bool Stru = this.btload("Struct");
        if (Stru)
        {
            this.btsetcurrent("Struct");
        }
    }
    private static string ExportedFilePath
    {
        get
        {
            string relativePath = "/Resources/behaviac/exported";

            return "Assets" + relativePath;
        }
    }

    private bool InitBehavic()
    {
        behaviac.Debug.LogWarning("InitBehavic");

        behaviac.Workspace.Instance.FilePath = ExportedFilePath;
        behaviac.Workspace.Instance.FileFormat = behaviac.Workspace.EFileFormat.EFF_xml;

        return true;
    }


    void Awake()
    {
        InitBehavic();
        InitPlayer();

    }

    behaviac.EBTStatus _status = behaviac.EBTStatus.BT_RUNNING;
    private void Start()
    {

        _status = this.btexec();
        FireEvent("event_task", 2);
    }
    void Update()
    {
        if (_status == behaviac.EBTStatus.BT_RUNNING)
        {
          //  behaviac.Debug.LogWarning("Update");


        }
    }
    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

