// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class SecondAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE SecondAgent
///<<< END WRITING YOUR CODE
{
	private int p3 = 0;
	public void _set_p3(int value)
	{
		p3 = value;
	}
	public int _get_p3()
	{
		return p3;
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

    void Awake()
    {
        FindObjectOfType<FisrtAgent>()._set_pInstance(this);

    }

    ///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

