// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_PROPERTIES_H_
#define _BEHAVIAC_AGENT_PROPERTIES_H_

#include "behaviac_agent_headers.h"
#include "behaviac_agent_member_visitor.h"
#include "behaviac_customized_types.h"

namespace behaviac
{
	// ---------------------------------------------------------------------
	// Delegate methods
	// ---------------------------------------------------------------------

	inline void FunctionPointer_behaviac_Agent_LogMessage(char* param0) { behaviac::Agent::LogMessage(param0); }

	inline void Set_FisrtAgent_P2(Agent* self, int value) { ((FisrtAgent*)self)->P2 = value; };
	inline const void* Get_FisrtAgent_P2(Agent* self) { return &((FisrtAgent*)self)->P2; };

	inline void Set_FisrtAgent_pInstance(Agent* self, SecondAgent* value) { ((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_pInstance, SecondAgent* >() = value; };
	inline const void* Get_FisrtAgent_pInstance(Agent* self) { return &((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_pInstance, SecondAgent* >(); };

	inline void Set_FisrtAgent_pp3(Agent* self, FirstStruct value) { ((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_pp3, FirstStruct >() = value; };
	inline const void* Get_FisrtAgent_pp3(Agent* self) { return &((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_pp3, FirstStruct >(); };

	inline void Set_FisrtAgent_type(Agent* self, FirstEnum value) { ((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_type, FirstEnum >() = value; };
	inline const void* Get_FisrtAgent_type(Agent* self) { return &((FisrtAgent*)self)->_Get_Property_<PROPERTY_TYPE_FisrtAgent_type, FirstEnum >(); };

	inline void FunctionPointer_FisrtAgent_event_task(Agent* self, int valur) { } /* event_task */
	inline void FunctionPointer_FisrtAgent_LogMessage(char* param0) { FisrtAgent::LogMessage(param0); }
	inline int FunctionPointer_FisrtAgent_PRe(Agent* self, int s) { return ((FisrtAgent*)self)->PRe(s); }
	inline void FunctionPointer_FisrtAgent_t1(Agent* self, int value) { } /* t1 */

	inline void Set_SecondAgent_p3(Agent* self, int value) { ((SecondAgent*)self)->_Get_Property_<PROPERTY_TYPE_SecondAgent_p3, int >() = value; };
	inline const void* Get_SecondAgent_p3(Agent* self) { return &((SecondAgent*)self)->_Get_Property_<PROPERTY_TYPE_SecondAgent_p3, int >(); };

	inline void FunctionPointer_SecondAgent_LogMessage(char* param0) { SecondAgent::LogMessage(param0); }
	inline void Set_FirstStruct_s1(Agent* self, int value) { ((FirstStruct*)self)->s1 = value; };
	inline const void* Get_FirstStruct_s1(Agent* self) { return &((FirstStruct*)self)->s1; };

	inline void Set_FirstStruct_s2(Agent* self, int value) { ((FirstStruct*)self)->s2 = value; };
	inline const void* Get_FirstStruct_s2(Agent* self) { return &((FirstStruct*)self)->s2; };

}
#endif // _BEHAVIAC_AGENT_PROPERTIES_H_
