// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct PROPERTY_TYPE_FisrtAgent_pInstance { };
template<> inline SecondAgent*& FisrtAgent::_Get_Property_<PROPERTY_TYPE_FisrtAgent_pInstance>()
{
	return this->pInstance;
}

struct PROPERTY_TYPE_FisrtAgent_pp3 { };
template<> inline FirstStruct& FisrtAgent::_Get_Property_<PROPERTY_TYPE_FisrtAgent_pp3>()
{
	return this->pp3;
}

struct PROPERTY_TYPE_FisrtAgent_type { };
template<> inline FirstEnum& FisrtAgent::_Get_Property_<PROPERTY_TYPE_FisrtAgent_type>()
{
	return this->type;
}

struct METHOD_TYPE_FisrtAgent_SayHello { };
template<> inline void FisrtAgent::_Execute_Method_<METHOD_TYPE_FisrtAgent_SayHello>(behaviac::string& p0)
{
	this->FisrtAgent::SayHello(p0);
}


struct PROPERTY_TYPE_SecondAgent_p3 { };
template<> inline int& SecondAgent::_Get_Property_<PROPERTY_TYPE_SecondAgent_p3>()
{
	return this->p3;
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
