// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_FISRTAGENT_H_
#define _BEHAVIAC_FISRTAGENT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class FisrtAgent : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE FisrtAgent
///<<< END WRITING YOUR CODE
{
public:
	FisrtAgent();
	virtual ~FisrtAgent();

	BEHAVIAC_DECLARE_AGENTTYPE(FisrtAgent, behaviac::Agent)

	public: int P2;

	private: SecondAgent* pInstance;

	private: FirstStruct pp3;

	private: FirstEnum type;

	public: void m1(behaviac::string& value);

	public: int PRe(int s);

	private: void SayHello(behaviac::string& value);

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
