// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#include "FisrtAgent.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

FisrtAgent::FisrtAgent()
{
	P2 = 0;
	pInstance = NULL;
	type = e1;
///<<< BEGIN WRITING YOUR CODE CONSTRUCTOR

///<<< END WRITING YOUR CODE
}

FisrtAgent::~FisrtAgent()
{
///<<< BEGIN WRITING YOUR CODE DESTRUCTOR

///<<< END WRITING YOUR CODE
}

void FisrtAgent::m1(behaviac::string& value)
{
///<<< BEGIN WRITING YOUR CODE m1
///<<< END WRITING YOUR CODE
}

int FisrtAgent::PRe(int s)
{
///<<< BEGIN WRITING YOUR CODE PRe
	return 0;
///<<< END WRITING YOUR CODE
}

void FisrtAgent::SayHello(behaviac::string& value)
{
///<<< BEGIN WRITING YOUR CODE SayHello
///<<< END WRITING YOUR CODE
}


///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE
